### PR TITLE
Chair environment model

### PR DESCRIPTION
**Pull request by anastasiabolotnikova**
This PR includes a chair environment model and all associated files (convex, meshes, surfaces).

This is a general chair model with realistic visual appearance. It might be useful in the future projects developing `mc_rtc` controllers, so this is why I suggest to add it to `mc_rtc_data`.

The model is suitable for being used with `mc_human` model (see attached image). Which makes it particularly useful for projects working on human-robot interaction.

chair

### CODE REVIEW

**Comment by gergondet** [comment]
Hi @anastasiabolotnikova 

Thanks for the PR. This is indeed useful to have in general. However, the surfaces' normal directions are surprising. Can you revert them or would that be too troublesome at this point?

**Comment by anastasiabolotnikova** [comment]
Hi @gergondet 

No trouble, 8c412ec2f0025abb080edf722c250eb71d3ce43d.

Now it's fixed

cahir

**Comment by gergondet** [comment]
Why is there no surface on the left handle is that a glitch in the visualization that happened right when you took the screenshot?

**Comment by anastasiabolotnikova** [comment]
Yes, it's just my RVIZ display settings. The surface is there

cahir

**Comment by gergondet** [comment]
Ok, great, will merge now. Thanks!

**Pull request merged**
